---
title: "Input longitudinal structure for acupuncture database"
author: "Steve Simon"
date: "Creation date: 2019-10-21"
output: html_document
---
```{r setup}
source("input-functions.R")
```

### Acupuncture

The source for this data set is

[TSHS Resources Portal](https://www.causeweb.org/tshs/acupuncture/)

```{r acupuncture}
nam <- "longitudinal_example"
tb0_name <- "demog_table"
tb1_name <- "baseline_table"
tb2_name <- "three_month_table"
tb3_name <- "one_year_table"
tb4_name <- "sex_table"
tb5_name <- "migraine_table"
tb6_name <- "group_table"
sql_name <- paste0("../data/", nam, "_db.sqlite")
dat_name <- paste0("../data/", nam, ".RData")

r_name <- "../data/acupuncture/acupuncture_data_reduced.RData"
load(r_name)
vnames <- names(data)
vnames <- gsub("group", "grp", vnames)
names(data) <- vnames

if (file.remove(sql_name)) cat(paste0(sql_name, " rewritten."))

data %>%
  select(id:grp) %>%
  add_to_sqlite(sql_name, tb0_name)

data %>%
  select(id, pk1) %>%
  filter(is.finite(pk1)) %>%
  add_to_sqlite(sql_name, tb1_name)

data %>%
  select(id, pk2) %>%
  filter(is.finite(pk2)) %>%
  add_to_sqlite(sql_name, tb2_name)

data %>%
  select(id, pk5) %>%
  filter(is.finite(pk5)) %>%
  add_to_sqlite(sql_name, tb3_name)

data.frame(
  sex_code=c(0, 1, 99), 
  sex_label=c("Male", "Female", "Unknown")) %>%
  add_to_sqlite(sql_name, tb4_name)

data.frame(
  migraine_code=c(0, 1, 98, 99), 
  migraine_label=c("Migraine", "Tension-type", "Other", "Unknown")) %>%
  add_to_sqlite(sql_name, tb5_name)

data.frame(
  group_code=c(0, 1), 
  group_label=c("Control", "Treatment")) %>%
  add_to_sqlite(sql_name, tb6_name)

table(is.finite(data$pk1), is.finite(data$pk2))
table(is.finite(data$pk1), is.finite(data$pk5))
table(is.finite(data$pk2), is.finite(data$pk5))

save.image(file=dat_name)
```