---
title: "Input unmatched label database"
author: "Steve Simon"
date: "Created October 16, 2019"
output: html_document
---

```{r setup}
source("input-functions.R")
```

### Unmatched labels

This is how to read in the Titanic data set.

```{r titanic}
csv_name <- "../data/unmatched_labels.csv"
sqlite_name <- "../data/unmatched_labels_db.sqlite"
table_name <- "results_table"

id <- 101:105
sex <- c(0, 1, 1, 0, 0)
sex_labels <- c("Male", "Female", "Did not answer")

big_table <- data.frame(id, sex)
small_table <- data.frame(sex=c(0, 1, 9), sex_labels)

write.csv(big_table, file=csv_name, row.names=FALSE)
add_to_sqlite(big_table, sqlite_name, table_name)

table_name <- "results_table"

sex_labels <- c("Male", "Female", "Did not answer")

small_table <- data.frame(sex=c(0, 1, 9), sex_labels)

write.csv(small_table, file=csv_name, row.names=FALSE)
add_to_sqlite(small_table, sqlite_name, table_name)
```

```{r save-everything}
rm(db)
save.image(file="../data/input-unmatched-labels.RData")
```