---
title: "Input unmatched label database"
author: "Steve Simon"
date: "Created October 16, 2019"
output: html_document
---

```{r setup}
source("input-functions.R")
```

### Unmatched labels

This code creates an artificial database to illustrate what happens when a label is mismatched.

```{r unmatched-labels}
nam <- "unmatched_labels"
cs1_name <- paste0("../data/", nam, "1.csv")
cs2_name <- paste0("../data/", nam, "2.csv")
sql_name <- paste0("../data/", nam, "_db.sqlite")
dat_name <- paste0("../data/", nam, ".RData")
tb1_name <- "results_table"
tb2_name <- "sex_table"

id <- 101:105
sex <- c(0, 1, 1, 0, 0)
sex_labels <- c("Male", "Female", "Did not answer")

df1 <- data.frame(id, sex)
df2 <- data.frame(sex=c(0, 1, 9), sex_labels)

write.csv(df1, file=cs1_name, row.names=FALSE)
add_to_sqlite(df1, sql_name, tb1_name)

sex_labels <- c("Male", "Female", "Did not answer")
df2 <- data.frame(sex=c(0, 1, 9), sex_labels)

write.csv(df2, file=cs2_name, row.names=FALSE)
add_to_sqlite(df2, sql_name, tb2_name)

save.image(file=dat_name)
```