---
title: "Learner support"
output: pdf_document
---

Academic Calendar: Students are encouraged to review important [add, drop or withdraw dates](http://www.umkc.edu/registrar/acal.asp).

Academic Honesty:
The Board of Curators of the University of Missouri recognizes that academic honesty is essential for the intellectual life of the University. Faculty members have a special obligation to expect high standards of academic honesty in all student work. Students have a special obligation to adhere to such standards. Academic dishonesty, including cheating, plagiarism or sabotage, is adjudicated through the University of Missouri Student Conduct Code (Links to an external site.) and Rules of Procedures in Student Conduct Matters (Links to an external site.).

Academic Inquiry, Course Discussion and Privacy:
Faculty not allowing recording
 University of Missouri System Executive Order No. 38 lays out principles regarding the sanctity of classroom discussions at the university. The policy is described fully in Section 200.015 of the Collected Rules and Regulations (Links to an external site.). In this class, students may not make any audio or video recordings of course activity (including those recordings prepared by an instructor), except students permitted to record as an accommodation under Section 240.040 of the Collected Rules. All other students who record and/or distribute audio or video recordings of class activity are subject to discipline in accordance with provisions of Section 200.020 of the Collected Rules and Regulations of the University of Missouri pertaining to student conduct matters.

Those students who have written permission from the course instructor to record are not permitted to redistribute any audio or video recordings of statements or comments from the course to individuals who are not students in the course without the express permission of the faculty member and of any students who are recorded, including those recordings prepared by an instructor. Students found to have violated this policy are subject to discipline in accordance with provisions of Section 200.020 of the Collected Rules and Regulations of the University of Missouri pertaining to student conduct matters.

Attendance Policy:
Students are expected to attend and participate in classes. In order to comply with federal regulations associated with eligibility rules for federal financial aid, students not attending a course during the first three weeks of the term will be administratively dropped from the specific course. Advance notice of attendance policies of academic units and individual instructors should be given, and such notice should be in writing. Students should notify instructors of excused absences in advance, where possible. Students who have an excused absence are expected to make arrangements with instructors for alternative or make-up work. Such arrangements should be made in advance of the absence, where possible. Instructors should accommodate excused absences to the extent that an accommodation can be made that does not unreasonably interfere with the learning objectives of the course or unduly burden the instructor. Attendance policies shall be applied in a non-discriminatory manner. Enrollment as a student is required to attend any class unless otherwise pre-approved by the instructor.  Instructors are responsible for verifying the class roster in Pathway throughout the term.

 https://catalog.umkc.edu/undergraduate-academic-regulations-information/attendance-policy/ (Links to an external site.) 

Campus Safety:
Inclement weather, mass notification, and emergency response guide: http://www.umkc.edu/umkcalert/ (Links to an external site.)

Counseling and Health Services Available at UMKC:
UMKC students may experience many challenges in their lives while attending college – stress, depression, suicidality, trauma, relationship issues, health concerns, etc.  As your professor I care about your success and well-being, and want to make you aware of some helpful resources on campus. The UMKC Counseling Center (www.umkc.edu/counselingcenter (Links to an external site.)), located at 4825 Troost in Room 206, offers a wide range of supportive services to students. Appointments can be made by calling 816.235.1635. UMKC Student Health and Wellness (http://info.umkc.edu/studenthealth/ (Links to an external site.)), located at 4825 Troost in Room 115, offers a full range of health care and promotion services.  Appointments can be scheduled online or by calling 816.235.6133. The MindBody Connection (www.umkc.edu/mindbody (Links to an external site.)) is located in the Atterbury Student Success Center in Room 112 and offers a variety of stress-reduction services.

Disability Support Services:
To obtain disability related accommodations and/or auxiliary aids, students with disabilities must contact the Office of Services for Students with Disabilities (OSSD) as soon as possible. To contact OSSD, call (816) 235-5696.  Once verified, OSSD will notify the course instructor and outline the accommodation and/or auxiliary aids to be provided.  For more information go to: http://www.umkc.edu/disability/ (Links to an external site.)

English Proficiency Statement:
Students who encounter difficulty in their courses because of the English proficiency of their instructors should speak directly with their instructors. If additional assistance is needed, students may contact the UMKC Help Line at 816-235-2222 for assistance.

Grade Appeal Policy:
Students are responsible for meeting the standards of academic performance established for each course in which they are enrolled. The establishment of the criteria for grades and the evaluation of student academic performance are the responsibilities of the instructor.

The University grade appeal procedure (Links to an external site.) is available only for the review of allegedly capricious grading and not for review of the instructor's evaluation of the student's academic performance. Capricious grading, as that term is used here, comprises any of the following:

The assignment of a grade to a particular student on some basis other than the performance in the course;

The assignment of a grade to a particular student according to more exacting or demanding standards than were applied to other students in the course; (Note: Additional or different grading criteria may be applied to graduate students enrolled for graduate credit in 300- and 400-level courses.)

The assignment of a grade by a substantial departure from the instructor's previously announced standards.

Discrimination Grievance Procedures for Students:
Discrimination Grievance Procedures for Students can be found here: http://www.umsystem.edu/ums/rules/collected_rules/grievance/ch390/grievance_390.010 (Links to an external site.)

Privacy and Accessibility Policies can be found here:  http://online.umkc.edu/faculty/teaching-resources/policies/ (Links to an external site.)   

Statement of Human Rights:
The Board of Curators and UMKC are committed to the policy of equal opportunity, regardless of race, color, religion, sex, sexual orientation, national origin, age, disability and status as a Vietnam era veteran. Commitment to the policy is mentored by the Office of Diversity and Inclusion (Links to an external site.), but it is the responsibility of the entire university community to provide equal opportunity through relevant practices, initiatives and programs.

Title IX:
Under the University of Missouri’s Title IX policy, discrimination, violence and harassment based on sex, gender, and gender identity are subject to the same kinds of accountability and support applied to offenses based on other protected characteristics such as race, color, ethnic or national origin, sexual orientation, religion, age, ancestry, disability, military status, and veteran status. If you or someone you know has been harassed or assaulted, you can find the appropriate resources by visiting UMKC’s Title IX Office webpage (http://info.umkc.edu/title9/ (Links to an external site.)) or contacting UMKC’s Title IX Coordinator, Mikah K. Thompson (816.235.6910 or thompsonmikah@umkc.edu).  Additionally, you can file a complaint using UMKC’s online discrimination complaint form, which is located at http://info.umkc.edu/title9/reporting/report-online/ (Links to an external site.).

While most UMKC employees are required to report any known or suspected violation of Title IX, students may seek confidential guidance from the following campus locations:

UMKC Counseling Service
Volker Campus
4825 Troost Ave, Suite 206
Kansas City, MO 64110

Phone – (816) 235-1635

Health Sciences Campus
Health Sciences Bldg 1418
2464 Charlotte
Kansas City, MO 64108
Phone – (816) 235-1635

(open Tuesdays, 1-5pm)

Student Health and Wellness
 (Links to an external site.)4825 Troost Ave., Suite 115
Kansas City, MO 64110
Phone – (816) 235-6133

UMKC Connect
Important information is available to undergraduate students in UMKC Connect accessed through Canvas.  Throughout the term, students may receive emails regarding course grades or academic performance. Students are expected to address information posted in a timely fashion.  This information may be shared with the student’s Success Network made up his or her academic advisor(s) and other campus resources so that UMKC may fully support the student’s success.

This file was written by Steve Simon and Suman Sahil on 2020-06-20 and last modified on `r Sys.Date()`.
