---
title: "Cholesterol upload to SQLite"
authors: Suman Sahil and Steve Simon
date: Created 2020-09-05
output: html_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../results", output_format = "all") })  
---

This file was last modified on `r Sys.Date()`.

This program reads a CSV file and loads into a table with the same name in the melange SQLite database.

```{r setup}
suppressMessages(suppressWarnings(library(sqldf)))
```

```{r write-sqlite}
file_name <- "cholesterol"
csv_name <- paste0(file_name, ".csv")
sqlite_name <- "melange.SQLite"
table_name <- file_name

db <- dbConnect(SQLite(), dbname=sqlite_name)
rawdata <- read.csv(csv_name)
dbWriteTable(
  conn=db, 
  name=table_name, 
  value=rawdata,
  overwrite=TRUE, 
  row.names=FALSE, 
  header=TRUE)
dbDisconnect(conn=db)
```

Check that everything works.

```{r check}
db <- dbConnect(SQLite(), dbname=sqlite_name)
dbListTables(db)
dbGetQuery(conn=db, "select * from cholesterol")
dbDisconnect(conn=db)
```