---
title: "Create overviews of key files for each module"
author: "Steve Simon"
date: "Created 2021-07-28"
output: html_document
---

```{r common-code, child="common-functions.Rmd"}
```

```{r}
list.files(path="../src", pattern="\\.Rmd") %>%
  str_subset("m..-hw") -> rmd_h

list.files(path="../src", pattern="\\.Rmd") %>%
  str_subset("m..-vi") -> rmd_v

list.files(path="../src", pattern="\\.sas") %>%
  str_subset("m..-hw") -> sas_h

list.files(path="../results", pattern="\\.pdf") %>%
  str_subset("m..-vi") -> pdf_v

list.files(path="../results", pattern="\\.pptx") %>%
  str_subset("m..-vi") -> ppt_v

list.files(path="../results", pattern="\\.pdf") %>%
  str_subset("-r-sqlite") -> rmd_o

list.files(path="../results", pattern="\\.pdf") %>%
  str_subset("-sas-oracle") -> sas_o

pdf_v %>% data.frame %>% set_names("pdf_v") %>% kable
ppt_v %>% data.frame %>% set_names("ppt_v") %>% kable
rmd_h %>% data.frame %>% set_names("rmd_h") %>% kable
rmd_o %>% data.frame %>% set_names("rmd_o") %>% kable
rmd_v %>% data.frame %>% set_names("rmd_v") %>% kable
sas_h %>% data.frame %>% set_names("sas_h") %>% kable
sas_o %>% data.frame %>% set_names("sas_o") %>% kable
```

```{r constants}
modules <- zpad(1:8)
prefix <- 'https://github.com/pmean/introduction-to-sql/blob/master/'
```

```{r write-module-resources}
resources_intro <- NULL
resources_readings_1 <- NULL
resources_readings_2 <- NULL
resources_slides_1 <- NULL
resources_slides_2 <- NULL
resources_homework_1 <- NULL
resources_homework_2 <- NULL
resources_conclusion <- NULL

for (i in 1:length(modules)) {
  module <- modules[i]
  module_num <- paste0("Module", module)
  pdf_v %>% str_subset(paste0("-m", module, "-")) -> pdf_v_subset
  ppt_v %>% str_subset(paste0("-m", module, "-")) -> ppt_v_subset
  rmd_h %>% str_subset(paste0("-m", module, "-")) -> rmd_h_subset
  rmd_o %>% str_subset(paste0("-m", module, "-")) -> rmd_o_subset
  rmd_v %>% str_subset(paste0("-m", module, "-")) -> rmd_v_subset
  sas_h %>% str_subset(paste0("-m", module, "-")) -> sas_h_subset
  sas_o %>% str_subset(paste0("-m", module, "-")) -> sas_o_subset
  filename <- str_replace("../modules/5508-xx-resources.md", "xx", module)

  vlist <- sort(c(pdf_v_subset, ppt_v_subset, rmd_v_subset))
  hlist <- sort(c(rmd_h_subset, rmd_o_subset, sas_h_subset, sas_o_subset))

  # resources_intro
  readLines("create-module-resources.txt") %>%
    paste0(collapse="\n")  %>%
    str_replace("Module", module_num) %>%
    str_replace ("the individual modules", module_num) %>%
    paste0("\n\n### Resources for ") %>%
    paste0(module_num) -> resources_intro[i]

  # resources_readings
  readings_filename <- paste0("../modules/5508-", module, "-readings.md")
  resources_readings <- readLines(con=readings_filename)
  i <- str_which(resources_readings, "---")[2]+1
  j <- str_which(resources_readings, "<!--links-->")
  n <- length(resources_readings)
  
  resources_readings %>%
    extract((i:(j-1))) %>%
    paste0(collapse="\n") %>%
    paste0("\n\nRecommended readings\n\n", .) -> resources_readings_1[i]
    
  resources_readings %>%
    extract(((j+1):n)) %>%
    paste0(collapse="\n") -> resources_readings_2[i]
    
  
  # resources_slides
  paste0("<!--resources-slides-1-->\n") %>%
    paste0("\n\n ") %>%
    paste0("Slides used in the videos\n") %>%
    paste0("\n", bullet(vlist)) -> resources_slides_1[i]
    
  paste0("\n\n<!---pdf_v--->") %>%
    paste0("\n", add_links(pdf_v_subset, "pdf", "results/")) %>%

    paste0("\n\n<!---ppt_v--->") %>%
    paste0("\n", add_links(ppt_v_subset, "ppt", "results/")) %>%
    
    paste0("\n\n<!---rmd_v--->") %>%
    paste0("\n", add_links(rmd_v_subset, "md", "src/")) -> resources_slides_2[i]

  # resources_homework
  resources_homework_1[i] <- "<!--resources-homework-1-->"
  resources_homework_2[i] <- "<!--resources-homework-2-->"
  if (length(hlist) > 0) {
    resources_homework_1[i] %>%
      paste0("\n\n ") %>%
      paste0("Homework solutions, code and output ") %>%
      paste0("from the previous module.\n\n")
      paste0("Compare your code to ours, ") %>%
      paste0("but only after submitting your work.\n") %>%
      paste0("\n", bullet(hlist)) -> resources_homework_1[i]
    
    resources_homework_2[i] %>%
      paste0("\n\n<!---rmd_o--->") %>%
      paste0("\n", add_links(rmd_o_subset, "pdf", "results/")) %>%
    
      paste0("\n\n<!---rmd_h--->") %>%
      paste0("\n", add_links(rmd_h_subset, "md", "src/")) %>%
    
      paste0("\n\n<!---sas_h--->") %>%
      paste0("\n", add_links(sas_h_subset, "sas", "src/")) %>%

      paste0("\n\n<!---sas_o--->") %>%
      paste0("\n", add_links(sas_o_subset, "sas", "src/")) -> resources_homework_1[i]
  }
  
  paste0("This information is also available on ") %>%
    paste0("[my github site][thisf].\n\n") %>%
    paste0("This file was automatically generated ") %>%
    paste0("by create-module-resources.Rmd") %>%
    paste0("and was last updated on ", Sys.Date()) %>%
    paste0(".\n\n") %>%
    paste0("The readme.md file on my github site has ") %>%
    paste0("[links to other important files][mygit].") %>%
      
    paste0("\n\n<!---my git--->") %>%
    paste0("\n[thisf]: ") %>%
    paste0(prefix) %>%
    paste0("modules/5508-") %>%
    paste0(module) %>%
    paste0("-resources.md") %>%
    
    paste0("\n[mygit]: ") %>%
    paste0(prefix) %>%
    paste0("README.md") -> resources_conclusion[i]

  
  resources_intro %>% 
    paste0(resources_readings_1[i]) %>%
    paste0("\n\n") %>%
    paste0(resources_slides_1[i]) %>%
    paste0("\n\n") %>%
    paste0(resources_homework_1[i-1]) %>%
    paste0("\n\n") %>%
    paste0(resources_conclusion[i]) %>%
    paste0("\n\n") %>%
    paste0(resources_readings_2[i]) %>%
    paste0("\n\n") %>%
    paste0(resources_slides_1[i]) %>%
    paste0("\n\n") %>%
    paste0(resources_homework_2[i-1]) -> resources_text
  
  resources_text %>% cat
  resources_text %>% writeLines(filename)
}
```


