---
title: "Homework-02-02"
author: "Steve Simon"
output:
  pdf_document: default
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, 
    encoding=encoding,
    output_dir = "../results", 
    output_format = "all") })  
---

This file was created on 2020-01-31 and last modified on `r Sys.Date()`.

Note: these solutions uses R and SQLite. An alternate solution using SAS and Oracle is also available.

Use the table crawling. Refer to the page "Data used in this module" for a description of the data and where you can download it. Oracle users do not need to download anything, but do need to use schema=melange in their code. Run a query that changes Temperature to Temperature_F and displays all three fields and all records.

Note: Some of the names used in this code are arbitrary and you can choose whatever names you want. To emphasize which names can be modified at your discretion, I am using names of famous statisticians.

The statistician being honored in this code is [William Edwards Deming](https://en.wikipedia.org/wiki/W._Edwards_Deming).

```{r}
library(sqldf)
deming <- dbConnect(SQLite(),
  dbname="../data/melange.sqlite")

edwards <- dbGetQuery(conn=deming, "
    select
      Birth_month,
      Temperature as Temperature_F,
      avg_crawling_age
      from crawling
")

edwards

dbDisconnect(conn=deming)
```