---
title: "Homework11a"
author: "Steve Simon"
output:
  pdf_document: default
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, 
    encoding=encoding,
    output_dir = "../results", 
    output_format = "all") })  
---

This file was created on 2020-07-24 and last modified on `r Sys.Date()`.

Note: this solution uses R and SQLite. An alternate solution using SAS and Oracle is also available.

Note: Some of the names used in this code are arbitrary and you can choose whatever names you want. To emphasize which names can be modified at your discretion, I am using names of famous statisticians.

The statistician being honored in this code is [George Box](https://en.wikipedia.org/wiki/George_E._P._Box).

Use the same database shown in the video. It is available on the Insights platform, or you can download a sqlite file from Canvas.

1. List id and migraine_label for the first ten records after joining the results_table and migraine_table.

2. Get a count of the number of records in the database in the control group and the treatment group. Use the label for group and not the number code.

3. Get a count of the numbers of males and females where you restrict age to be less than 40. Use the label for sex, but convert it to all uppercase.

```{r george_box1}
library(sqldf)
box <- dbConnect(SQLite(),
  dbname="../data/accupuncture.sqlite")
george1 <- dbGetQuery(conn=box,  "
    select tbl_name from sqlite_master
")

george1
dbDisconnect(conn=box)
```

