---
title: "Overview of Module 7: Single row functions"
author: "Suman Sahil, Steve Simon"
output:
  html_document: default
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../results", output_format = "all") })  
---

This file was created on 2020-07-07 and last modified on `r Sys.Date()`.

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
suppressMessages(suppressWarnings(library(knitr)))
suppressMessages(suppressWarnings(library(magrittr)))
suppressMessages(suppressWarnings(library(sqldf)))
git <- "https://github.com/pmean/introduction-to-sql/blob/master/"
pan <- "https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id="
```

### Objectives

+ In this module, you will learn how to:
  + Describe various types of functions available in SQL
  + Use character, number, and date functions in SELECT statements
  + Learn different types of single-row functions.
    + Character
    + Number
    + Date
    + Conversion
    + General
+ Please note that a few of the single row functions in the videos are not available for SQLite or are slight variations. For a list of SQL single-row functions, please look [here](https://www.sqlite.org/lang_corefunc.html). 
  + Here are some functions not available in SQLite.
    + The case conversion function, initcap.
    + The character conversion functions concat, lpad, or rpad, but there is an [alternative for concat](https://www.sqlitetutorial.net/sqlite-string-functions/sqlite-concat/).
    + The number functions mod or trunc, but there is an [alternative for mod](https://www.w3resource.com/sqlite/arithmetic-operators.php).
    + The general functions, nvl and decode.
  + SQLite has a slightly different approach (Links to an external site.) for displaying and manipulating dates. None of these issues will affect any of the homework exercises.

### SQL keywords

+ Here are the SQL keywords introduced in this module:
  + add_months
  + concat
  + decode
  + initcap
  + instr
  + last_day
  + length
  + lower
  + lpad
  + mod
  + months_between
  + next_day
  + nullif
  + nvl
  + round
  + rpad
  + substr
  + trim
  + trunc
  + upper

### Videos and handouts

+ Video07a. Single row functions to customize output (11 minutes)
  + Available in [Panopto format](`r pan`60a366ed-290e-4858-a9cc-aac3011d23ca)
  + Slides, available in [pdf format](`r git`results/video07a.pdf)
+ Video07b. Date and general functions (11 minutes)
  + Available in [Panopto format](`r pan`afef21f6-2a3a-456d-8468-aac4016e8dd3)
  + Slides (use the slides link for Video07a)
+ Video07c. Executing single row functions to customize output (11 minutes)
  + Available in [Panopto format](`r pan`afef21f6-2a3a-456d-8468-aac4016e8dd3)
  + Slides (use the slides link for Video07a)
  
### Datasets used in this module

This page provides a bit more details about the database used in this module. Please note that there might be small inconsistencies between the Oracle version and the SQLite version of the data.

Hospital and Titanic are used in the videos. Hospital is also used in the homework assignment.

+ Hospital
  + Data dictionary.  Available in [text format](`r git`data/hospital-data-dictionary.txt)
  + Oracle: no download needed
  + SQLite: download this file. Available in [binary format](`r git`data/hospital.sqlite).
  + You should not need it, but there is a backup of this data available in [CSV format](`r git`data/hospital.csv).

+ Titanic
  + Data dictionary.  Available in [text format](`r git`data/titanic-data-dictionary.txt)
  + Oracle: no download needed
  + SQLite: download this file. Available in [binary format](`r git`data/titanic.sqlite).
  + You should not need it, but there is a backup of this data available in [CSV format](`r git`data/titanic.csv).

### Discussion07a: One minute feedback

Graded: 3 points, one point deduction if submitted after deadline

Review the videos in this module and briefly answer the following questions

+ What was the most important thing that you learned?
+ What concept(s) do you still find confusing?
+ What would you like to learn next?

Please keep your answers brief. You are welcome to say something generic like "I found nothing confusing" or "I found everything confusing" or "I agree with the previous comment."

### Discussion07b: Review this week's readings

Graded: 3 points, one point deduction if submitted late.

Review the reading provide in this module and provide a brief summary (3 or 4 sentences). Was there anything in this reading that surprised you.

### Homework07a: 

Graded: 3 points, one point deduction if submitted after deadline

Your homework

+ Round the value 29.526 to two decimal places.
+ Truncate the value 29.526 to zero decimal places.
+ Calculate the remainder of the value 2500 after it is divided by 500
+ Put your code and output in a single pdf file

Please note that if you use Oracle, you will need the code "from dual" as part of your query. That code is not needed for SQLite.

### Quiz07

Graded: 3 points, one point deduction if submitted late.

Please create a single PDF file that includes both our questions and your answers to the following.


