---
title: "Overview of Module 6: Null values"
author: "Suman Sahil, Steve Simon"
output:
  html_document: default
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../results", output_format = "all") })  
---

This file was created on 2020-07-05 and last modified on `r Sys.Date()`.

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
suppressMessages(suppressWarnings(library(knitr)))
suppressMessages(suppressWarnings(library(magrittr)))
suppressMessages(suppressWarnings(library(sqldf)))
git <- "https://github.com/pmean/introduction-to-sql/blob/master/"
pan <- "https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id="
```

### Objectives

+ In this module, you will learn how to:
  + count missing and non-missing values
  + recognize how missing values influence averages and counts

### SQL keywords

+ Here are the SQL keywords introduced in this module:
  + avg
  + count
  + is null, is not null

### Videos and handouts

+ Video06a. Null values, part 1 (13 minutes)
  + Available in [Panopto format](`r pan`873a9bdc-1bad-47c7-8e1b-aac4013aa333)
  + Slides, available in [pdf format](`r git`results/video06a.pdf)
+ Video06b. Null values, part 2 (23 minutes)
  + Available in [Panopto format](`r pan`0d481f87-e7c2-49c2-a933-aac4013e693f)
  + Slides (use the slides link for Video06a)
  
### Datasets used in this module

This page provides a bit more details about the database used in this module. Please note that there might be small inconsistencies between the Oracle version and the SQLite version of the data.

Hospital and Titanic are used in the videos. Hospital is also used in the homework assignment.

+ Hospital
  + Data dictionary.  Available in [text format](`r git`data/hospital-data-dictionary.txt)
  + Oracle: no download needed
  + SQLite: download this file. Available in [binary format](`r git`data/hospital.sqlite).
  + You should not need it, but there is a backup of this data available in [CSV format](`r git`data/hospital.csv).

+ Titanic
  + Data dictionary.  Available in [text format](`r git`data/titanic-data-dictionary.txt)
  + Oracle: no download needed
  + SQLite: download this file. Available in [binary format](`r git`data/titanic.sqlite).
  + You should not need it, but there is a backup of this data available in [CSV format](`r git`data/titanic.csv).

### Discussion06a: One minute feedback

Graded: 3 points, one point deduction if submitted after deadline

Review the videos in this module and briefly answer the following questions

+ What was the most important thing that you learned?
+ What concept(s) do you still find confusing?
+ What would you like to learn next?

Please keep your answers brief. You are welcome to say something generic like "I found nothing confusing" or "I found everything confusing" or "I agree with the previous comment."

### Discussion06b: Review this week's readings

Graded: 3 points, one point deduction if submitted late.

Review the reading provide in this module and provide a brief summary (3 or 4 sentences). Was there anything in this reading that surprised you.

### Homework06a: 

Graded: 3 points, one point deduction if submitted after deadline.

For your homework, use the hospital database that I mentioned briefly earlier in this lecture.

1. Verify that the hospital id code (HOSP_ID) has no missing values.
2. here are only two fields in the database that have null values. Get a count of the number of missing values for the indicator for teaching hospital (TEACHING_IND).
3. There is only one hospital where the number of beds (BED_SIZE) is unknown. Find the id of that hospital.
4. Combine your results into a single PDF file and submit it.

### Quiz06

Graded: 3 points, one point deduction if submitted late.

Please create a single PDF file that includes both our questions and your answers to the following.

1. Why does the code "where age=NULL" fail to produce any records?

2. What codes are NULL values converted to in SAS?

3. How do the statistical summary functions like AVG and COUNT handle missing values?

